"""Updated users table and Sessions

Revision ID: 09363b480be8
Revises: 1979602e79d4
Create Date: 2026-01-25 01:07:26.636397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09363b480be8'
down_revision: Union[str, Sequence[str], None] = '1979602e79d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('performed_by', sa.String(length=255), nullable=True, comment="Email of user or 'system_owner_script'"))
    op.add_column('audit_logs', sa.Column('before', sa.JSON(), nullable=True, comment='State before action'))
    op.add_column('audit_logs', sa.Column('after', sa.JSON(), nullable=True, comment='State after action'))
    op.alter_column('audit_logs', 'changes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_index(op.f('ix_audit_logs_performed_by'), 'audit_logs', ['performed_by'], unique=False)
    op.add_column('users', 
        sa.Column('is_system_owner', sa.Boolean(), nullable=True, server_default='false')
    )
    
    # Make organization_id nullable for system owner
    op.alter_column('users', 'organization_id',
        existing_type=postgresql.UUID(),
        nullable=True
    )
    
    # Update existing users to have is_system_owner = false
    op.execute("UPDATE users SET is_system_owner = false WHERE is_system_owner IS NULL")
    
    # Now make is_system_owner non-nullable with default
    op.alter_column('users', 'is_system_owner',
        existing_type=sa.Boolean(),
        nullable=False,
        server_default='false'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('users', 'is_system_owner')
    op.drop_index(op.f('ix_audit_logs_performed_by'), table_name='audit_logs')
    op.alter_column('audit_logs', 'changes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('audit_logs', 'after')
    op.drop_column('audit_logs', 'before')
    op.drop_column('audit_logs', 'performed_by')
    # ### end Alembic commands ###
