"""Updated the Lead Table

Revision ID: 57bf97489d2c
Revises: d3c50a3a33e5
Create Date: 2026-01-31 21:40:54.877362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57bf97489d2c'
down_revision: Union[str, Sequence[str], None] = 'd3c50a3a33e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1️⃣ Backfill existing NULL values
    op.execute(
        "UPDATE leads SET tags = '{}' WHERE tags IS NULL"
    )

    # 2️⃣ Set default + NOT NULL
    op.alter_column(
        'leads',
        'tags',
        existing_type=postgresql.ARRAY(sa.TEXT()),
        server_default=sa.text("'{}'"),
        nullable=False
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
